// lib/catalog.mjs — settings-page data tables moved verbatim from index.mjs
// (import-free, no @deepseek-ai dependency — node builtins only, none used
// here). The /options tool-directory builder itself stays in index.mjs for now:
// it reads ctx.tools/agentPresets (non-pure), so it is not part of this module.

// Tool-name → 中文说明 map, shown beside the raw tool name in the toolFilter
// picker. Tools absent here fall back to their raw name.
export const TOOL_ZH = {
  'bash': '终端命令',
  'pwsh': 'PowerShell 命令',
  'read': '读取文件',
  'write': '写入文件',
  'edit': '编辑文件',
  'grep': '搜索文件内容',
  'glob': '查找文件',
  'web_search': '网页搜索',
  'browser_navigate': '浏览器打开网址',
  'browser_snapshot': '浏览器页面快照',
  'browser_click': '浏览器点击',
  'browser_type': '浏览器输入',
  'browser_scroll': '浏览器滚动',
  'browser_back': '浏览器后退',
  'browser_forward': '浏览器前进',
  'browser_press': '浏览器按键',
  'browser_reload': '浏览器刷新',
  'browser_wait': '浏览器等待',
  'browser_get_text': '读取页面文本',
  'dispatch': '派发子 Agent',
  'subagent': '派生子 Agent',
  'subagent_fork': '派生子 Agent（继承上下文）',
  'send_message': '给子 Agent 发消息',
  'interrupt_agent': '中断子 Agent',
  'list_agents': '列出子 Agent',
  'todo_write': '任务清单',
  'create_goal': '创建目标',
  'get_goal': '查看目标',
  'update_goal': '更新目标',
  'workflow': '编排多 Agent 工作流',
  'ralph': 'Ralph 迭代',
  'ask_user_question': '询问用户',
  'skill': '加载技能',
  'describe_image': '描述图片',
  'read_image': '读取图片',
  'modlens_read_image': '读取图片（modlens）',
  'ssh_list': '列出 SSH 主机',
  'ssh_exec': 'SSH 执行命令',
  'ssh_upload': 'SSH 上传',
  'ssh_download': 'SSH 下载',
  'ssh_tunnel': 'SSH 隧道',
  'ssh_cluster': 'SSH 集群执行',
  'exit_plan_mode': '退出计划模式',
  'incident_resolved': '标记事故已解决',
  'dsh_rollback': '回滚 DSH',
  'dsh_snapshot': 'DSH 快照',
  'job_list': '列出后台任务',
  'job_output': '读取后台任务输出',
  'job_kill': '终止后台任务',
  'str_replace_editor': '文本编辑',
  'cordis_inspect_list': '列出 Cordis 服务',
  'cordis_inspect_query': '查询 Cordis 服务',
  'cordis_inspect_self': '查看自身 Cordis 服务',
  'cordis_define': '定义 Cordis 服务',
  'cordis_run': '运行 Cordis 服务',
  'cordis_stop': '停止 Cordis 服务',
  'cordis_undefine': '取消定义 Cordis 服务',
  'run_code': '运行代码',
};

// Tool-name → 功能分类 map，覆盖 DSH 官方核心工具（固定集合）。插件工具
// 走前缀提取（见 categoryOf），自建预设用 preset 名。
export const TOOL_CATEGORY = {
  'read': '文件', 'write': '文件', 'edit': '文件', 'grep': '文件', 'glob': '文件', 'str_replace_editor': '文件',
  'bash': '终端', 'pwsh': '终端',
  'web_search': '网络',
  'todo_write': '任务', 'create_goal': '任务', 'get_goal': '任务', 'update_goal': '任务',
  'subagent': '子 Agent', 'subagent_fork': '子 Agent', 'send_message': '子 Agent', 'interrupt_agent': '子 Agent', 'list_agents': '子 Agent',
  'workflow': '工作流', 'ralph': '工作流',
  'ask_user_question': '交互', 'skill': '交互',
  'read_image': '图片', 'describe_image': '图片',
  'cordis_inspect_list': 'Cordis', 'cordis_inspect_query': 'Cordis', 'cordis_inspect_self': 'Cordis',
  'cordis_define': 'Cordis', 'cordis_run': 'Cordis', 'cordis_stop': 'Cordis', 'cordis_undefine': 'Cordis',
  'exit_plan_mode': '计划',
};
